"""Modelo inicial (seção 3), papéis do banco e Row Level Security por cliente.

Papéis (NOLOGIN; usuários de login recebem um deles via GRANT):
- monitor_api: sujeito ao RLS; lê a base compartilhada e só as linhas do próprio cliente.
- monitor_sistema: BYPASSRLS; workers e motor de regras.
Criar papel com BYPASSRLS exige executar a migração como superusuário.

Revision ID: 0001
Revises:
Create Date: 2026-09-24 01:33:59.308696
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Congelado nesta revisão (não importar de db.modelos: migrações não mudam depois de aplicadas).
TABELAS_CLIENTE = ("alvo", "regra", "ocorrencia", "alerta", "auditoria")
TABELAS_COMPARTILHADAS = (
    "tribunal",
    "tribunal_unidade",
    "processo",
    "pessoa",
    "parte",
    "advogado",
    "movimento",
    "coleta_bruta",
    "execucao_robo",
)
# O que a API pode ler da base compartilhada (coleta_bruta fica de fora).
LEITURA_API = tuple(t for t in TABELAS_COMPARTILHADAS if t != "coleta_bruta")
TODAS = (*TABELAS_COMPARTILHADAS, "cliente", *TABELAS_CLIENTE)
CLIENTE_ATUAL = "NULLIF(current_setting('app.cliente_id', true), '')::bigint"


def _criar_papeis() -> None:
    op.execute(
        """
        DO $$
        BEGIN
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'monitor_api') THEN
            CREATE ROLE monitor_api NOLOGIN NOBYPASSRLS;
          END IF;
          IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'monitor_sistema') THEN
            CREATE ROLE monitor_sistema NOLOGIN BYPASSRLS;
          END IF;
        END
        $$;
        """
    )


def _permissoes() -> None:
    op.execute("GRANT USAGE ON SCHEMA public TO monitor_api, monitor_sistema")
    op.execute(f"GRANT SELECT ON {', '.join(LEITURA_API)} TO monitor_api")
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON alvo, regra, ocorrencia, alerta TO monitor_api"
    )
    op.execute("GRANT SELECT, UPDATE ON cliente TO monitor_api")
    # Auditoria é somente inserção (trilha imutável para a API).
    op.execute("GRANT SELECT, INSERT ON auditoria TO monitor_api")

    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON "
        f"{', '.join(t for t in TODAS if t != 'auditoria')} TO monitor_sistema"
    )
    op.execute("GRANT SELECT, INSERT ON auditoria TO monitor_sistema")


def _rls() -> None:
    op.execute("ALTER TABLE cliente ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE cliente FORCE ROW LEVEL SECURITY")
    op.execute(
        f"CREATE POLICY isolamento_cliente ON cliente "
        f"USING (id = {CLIENTE_ATUAL}) WITH CHECK (id = {CLIENTE_ATUAL})"
    )
    for tabela in TABELAS_CLIENTE:
        op.execute(f"ALTER TABLE {tabela} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {tabela} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY isolamento_cliente ON {tabela} "
            f"USING (cliente_id = {CLIENTE_ATUAL}) WITH CHECK (cliente_id = {CLIENTE_ATUAL})"
        )


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    _criar_papeis()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cliente",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("cnpj", sa.String(length=14), nullable=True),
        sa.Column("plano", sa.String(length=30), server_default="padrao", nullable=False),
        sa.Column(
            "contatos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cliente")),
    )
    op.create_table(
        "pessoa",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("documento", sa.String(length=14), nullable=True),
        sa.Column("tipo", sa.String(length=2), nullable=True),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("nome_normalizado", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "documento ~ '^([0-9]{11}|[0-9A-Z]{12}[0-9]{2})$'",
            name=op.f("ck_pessoa_documento_formato"),
        ),
        sa.CheckConstraint("tipo IN ('PF', 'PJ')", name=op.f("ck_pessoa_tipo")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pessoa")),
    )
    op.create_index(
        "ix_pessoa_nome_normalizado_trgm",
        "pessoa",
        ["nome_normalizado"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"nome_normalizado": "gin_trgm_ops"},
    )
    op.create_index(
        "uq_pessoa_documento",
        "pessoa",
        ["documento"],
        unique=True,
        postgresql_where=sa.text("documento IS NOT NULL"),
    )
    op.create_table(
        "tribunal",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sigla", sa.String(length=20), nullable=False),
        sa.Column("sistema", sa.String(length=10), nullable=False),
        sa.Column("grau", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("limite_req_min", sa.Integer(), server_default="12", nullable=False),
        sa.CheckConstraint("sistema IN ('esaj', 'eproc', 'pje')", name=op.f("ck_tribunal_sistema")),
        sa.CheckConstraint("grau IN (1, 2)", name=op.f("ck_tribunal_grau")),
        sa.CheckConstraint("limite_req_min > 0", name=op.f("ck_tribunal_limite_req_min")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tribunal")),
        sa.UniqueConstraint(
            "sigla", "sistema", "grau", name=op.f("uq_tribunal_sigla_sistema_grau")
        ),
    )
    op.create_table(
        "alvo",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("valor", sa.Text(), nullable=False),
        sa.Column(
            "variacoes", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("prioridade", sa.String(length=10), server_default="padrao", nullable=False),
        sa.Column("finalidade", sa.Text(), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("prioridade IN ('critica', 'padrao')", name=op.f("ck_alvo_prioridade")),
        sa.CheckConstraint("tipo IN ('documento', 'nome')", name=op.f("ck_alvo_tipo")),
        sa.CheckConstraint("length(trim(finalidade)) > 0", name=op.f("ck_alvo_finalidade")),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_alvo_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alvo")),
        sa.UniqueConstraint(
            "cliente_id", "tipo", "valor", name=op.f("uq_alvo_cliente_id_tipo_valor")
        ),
        sa.UniqueConstraint("id", "cliente_id", name=op.f("uq_alvo_id_cliente_id")),
    )
    op.create_index("ix_alvo_tipo_valor", "alvo", ["tipo", "valor"], unique=False)
    op.create_table(
        "auditoria",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=True),
        sa.Column("usuario_id", sa.BigInteger(), nullable=True),
        sa.Column("acao", sa.Text(), nullable=False),
        sa.Column("entidade", sa.Text(), nullable=False),
        sa.Column("entidade_id", sa.Text(), nullable=True),
        sa.Column(
            "em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "detalhes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_auditoria_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auditoria")),
    )
    op.create_index("ix_auditoria_cliente_em", "auditoria", ["cliente_id", "em"], unique=False)
    op.create_table(
        "coleta_bruta",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo_consulta", sa.String(length=10), nullable=False),
        sa.Column("parametro_hash", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=True),
        sa.Column("objeto_storage", sa.Text(), nullable=False),
        sa.Column(
            "coletado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo_consulta IN ('documento', 'nome', 'processo')", name=op.f("ck_coleta_bruta_tipo")
        ),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_coleta_bruta_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coleta_bruta")),
    )
    op.create_index(
        "ix_coleta_bruta_cache",
        "coleta_bruta",
        ["tribunal_id", "tipo_consulta", "parametro_hash", "coletado_em"],
        unique=False,
    )
    op.create_table(
        "execucao_robo",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "iniciado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finalizado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consultas", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sucesso", sa.Integer(), server_default="0", nullable=False),
        sa.Column("erros", sa.Integer(), server_default="0", nullable=False),
        sa.Column("processos_novos", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_execucao_robo_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execucao_robo")),
    )
    op.create_index(
        "ix_execucao_robo_tribunal_inicio",
        "execucao_robo",
        ["tribunal_id", "iniciado_em"],
        unique=False,
    )
    op.create_table(
        "processo",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("numero_cnj", sa.String(length=25), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column("classe_codigo", sa.Integer(), nullable=True),
        sa.Column("classe_nome", sa.Text(), nullable=True),
        sa.Column(
            "assuntos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("comarca", sa.Text(), nullable=True),
        sa.Column("foro", sa.Text(), nullable=True),
        sa.Column("vara", sa.Text(), nullable=True),
        sa.Column("data_distribuicao", sa.Date(), nullable=True),
        sa.Column("valor_causa_centavos", sa.BigInteger(), nullable=True),
        sa.Column("segredo", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("status_coleta", sa.String(length=10), server_default="pendente", nullable=False),
        sa.Column(
            "primeira_coleta_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "numero_cnj ~ '^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$'",
            name=op.f("ck_processo_numero_cnj_formato"),
        ),
        sa.CheckConstraint(
            "status_coleta IN ('pendente', 'completo', 'sigiloso', 'erro')",
            name=op.f("ck_processo_status_coleta"),
        ),
        sa.CheckConstraint("valor_causa_centavos >= 0", name=op.f("ck_processo_valor_causa")),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_processo_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processo")),
        sa.UniqueConstraint("numero_cnj", name=op.f("uq_processo_numero_cnj")),
    )
    op.create_index(op.f("ix_processo_comarca"), "processo", ["comarca"], unique=False)
    op.create_index(
        op.f("ix_processo_data_distribuicao"), "processo", ["data_distribuicao"], unique=False
    )
    op.create_index(op.f("ix_processo_tribunal_id"), "processo", ["tribunal_id"], unique=False)
    op.create_table(
        "regra",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("finalidade", sa.Text(), nullable=False),
        sa.Column(
            "classes",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "assuntos",
            postgresql.ARRAY(sa.Integer()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "termos", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "comarcas", postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("polo", sa.String(length=10), nullable=True),
        sa.Column("valor_min_centavos", sa.BigInteger(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("polo IN ('ativo', 'passivo', 'terceiro')", name=op.f("ck_regra_polo")),
        sa.CheckConstraint("length(trim(finalidade)) > 0", name=op.f("ck_regra_finalidade")),
        sa.CheckConstraint("valor_min_centavos >= 0", name=op.f("ck_regra_valor_min")),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_regra_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regra")),
        sa.UniqueConstraint("id", "cliente_id", name=op.f("uq_regra_id_cliente_id")),
    )
    op.create_index(op.f("ix_regra_cliente_id"), "regra", ["cliente_id"], unique=False)
    op.create_table(
        "tribunal_unidade",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column("comarca", sa.Text(), nullable=False),
        sa.Column("competencia", sa.Text(), nullable=False),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_tribunal_unidade_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tribunal_unidade")),
        sa.UniqueConstraint(
            "tribunal_id",
            "comarca",
            "competencia",
            "vigente_desde",
            name=op.f("uq_tribunal_unidade_tribunal_id_comarca_competencia_vigente_desde"),
        ),
    )
    op.create_index(
        op.f("ix_tribunal_unidade_tribunal_id"), "tribunal_unidade", ["tribunal_id"], unique=False
    )
    op.create_table(
        "movimento",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("processo_id", sa.BigInteger(), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("codigo_tpu", sa.Integer(), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["processo_id"],
            ["processo.id"],
            name=op.f("fk_movimento_processo_id_processo"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_movimento")),
        sa.UniqueConstraint("processo_id", "hash", name=op.f("uq_movimento_processo_id_hash")),
    )
    op.create_table(
        "ocorrencia",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("processo_id", sa.BigInteger(), nullable=False),
        sa.Column("alvo_id", sa.BigInteger(), nullable=True),
        sa.Column("regra_id", sa.BigInteger(), nullable=True),
        sa.Column("confianca", sa.String(length=12), nullable=False),
        sa.Column("score_urgencia", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "detectado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=10), server_default="novo", nullable=False),
        sa.CheckConstraint(
            "confianca IN ('confirmada', 'a_verificar')", name=op.f("ck_ocorrencia_confianca")
        ),
        sa.CheckConstraint(
            "status IN ('novo', 'visto', 'descartado')", name=op.f("ck_ocorrencia_status")
        ),
        sa.CheckConstraint(
            "num_nonnulls(alvo_id, regra_id) = 1", name=op.f("ck_ocorrencia_alvo_ou_regra")
        ),
        sa.CheckConstraint(
            "score_urgencia BETWEEN 0 AND 100", name=op.f("ck_ocorrencia_score_urgencia")
        ),
        sa.ForeignKeyConstraint(
            ["alvo_id", "cliente_id"],
            ["alvo.id", "alvo.cliente_id"],
            name=op.f("fk_ocorrencia_alvo_id_cliente_id_alvo"),
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_ocorrencia_cliente_id_cliente")
        ),
        sa.ForeignKeyConstraint(
            ["processo_id"], ["processo.id"], name=op.f("fk_ocorrencia_processo_id_processo")
        ),
        sa.ForeignKeyConstraint(
            ["regra_id", "cliente_id"],
            ["regra.id", "regra.cliente_id"],
            name=op.f("fk_ocorrencia_regra_id_cliente_id_regra"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocorrencia")),
        sa.UniqueConstraint("id", "cliente_id", name=op.f("uq_ocorrencia_id_cliente_id")),
        sa.UniqueConstraint(
            "processo_id", "alvo_id", name=op.f("uq_ocorrencia_processo_id_alvo_id")
        ),
        sa.UniqueConstraint(
            "processo_id", "regra_id", name=op.f("uq_ocorrencia_processo_id_regra_id")
        ),
    )
    op.create_index(
        "ix_ocorrencia_cliente_status_detectado",
        "ocorrencia",
        ["cliente_id", "status", "detectado_em"],
        unique=False,
    )
    op.create_table(
        "parte",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("processo_id", sa.BigInteger(), nullable=False),
        sa.Column("pessoa_id", sa.BigInteger(), nullable=False),
        sa.Column("polo", sa.String(length=10), nullable=False),
        sa.Column("tipo_participacao", sa.Text(), nullable=True),
        sa.CheckConstraint("polo IN ('ativo', 'passivo', 'terceiro')", name=op.f("ck_parte_polo")),
        sa.ForeignKeyConstraint(
            ["pessoa_id"], ["pessoa.id"], name=op.f("fk_parte_pessoa_id_pessoa")
        ),
        sa.ForeignKeyConstraint(
            ["processo_id"],
            ["processo.id"],
            name=op.f("fk_parte_processo_id_processo"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parte")),
        sa.UniqueConstraint(
            "processo_id", "pessoa_id", "polo", name=op.f("uq_parte_processo_id_pessoa_id_polo")
        ),
    )
    op.create_index(op.f("ix_parte_pessoa_id"), "parte", ["pessoa_id"], unique=False)
    op.create_table(
        "advogado",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("parte_id", sa.BigInteger(), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("oab_numero", sa.String(length=20), nullable=True),
        sa.Column("oab_uf", sa.String(length=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["parte_id"], ["parte.id"], name=op.f("fk_advogado_parte_id_parte"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_advogado")),
    )
    op.create_index(op.f("ix_advogado_parte_id"), "advogado", ["parte_id"], unique=False)
    op.create_table(
        "alerta",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("ocorrencia_id", sa.BigInteger(), nullable=False),
        sa.Column("canal", sa.String(length=10), nullable=False),
        sa.Column("destino", sa.Text(), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("enviado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_envio", sa.String(length=10), server_default="pendente", nullable=False),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "canal IN ('email', 'whatsapp', 'webhook')", name=op.f("ck_alerta_canal")
        ),
        sa.CheckConstraint(
            "status_envio IN ('pendente', 'enviado', 'falhou')", name=op.f("ck_alerta_status_envio")
        ),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_alerta_cliente_id_cliente")
        ),
        sa.ForeignKeyConstraint(
            ["ocorrencia_id", "cliente_id"],
            ["ocorrencia.id", "ocorrencia.cliente_id"],
            name=op.f("fk_alerta_ocorrencia_id_cliente_id_ocorrencia"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerta")),
    )
    op.create_index("ix_alerta_ocorrencia_id", "alerta", ["ocorrencia_id"], unique=False)
    # ### end Alembic commands ###

    _permissoes()
    _rls()


def downgrade() -> None:
    # As políticas somem junto com as tabelas. Os papéis e a extensão pg_trgm são do
    # cluster/banco e podem estar em uso por outros bancos: só revogamos o acesso ao schema.
    op.execute("REVOKE USAGE ON SCHEMA public FROM monitor_api, monitor_sistema")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_alerta_ocorrencia_id", table_name="alerta")
    op.drop_table("alerta")
    op.drop_index(op.f("ix_advogado_parte_id"), table_name="advogado")
    op.drop_table("advogado")
    op.drop_index(op.f("ix_parte_pessoa_id"), table_name="parte")
    op.drop_table("parte")
    op.drop_index("ix_ocorrencia_cliente_status_detectado", table_name="ocorrencia")
    op.drop_table("ocorrencia")
    op.drop_table("movimento")
    op.drop_index(op.f("ix_tribunal_unidade_tribunal_id"), table_name="tribunal_unidade")
    op.drop_table("tribunal_unidade")
    op.drop_index(op.f("ix_regra_cliente_id"), table_name="regra")
    op.drop_table("regra")
    op.drop_index(op.f("ix_processo_tribunal_id"), table_name="processo")
    op.drop_index(op.f("ix_processo_data_distribuicao"), table_name="processo")
    op.drop_index(op.f("ix_processo_comarca"), table_name="processo")
    op.drop_table("processo")
    op.drop_index("ix_execucao_robo_tribunal_inicio", table_name="execucao_robo")
    op.drop_table("execucao_robo")
    op.drop_index("ix_coleta_bruta_cache", table_name="coleta_bruta")
    op.drop_table("coleta_bruta")
    op.drop_index("ix_auditoria_cliente_em", table_name="auditoria")
    op.drop_table("auditoria")
    op.drop_index("ix_alvo_tipo_valor", table_name="alvo")
    op.drop_table("alvo")
    op.drop_table("tribunal")
    op.drop_index(
        "uq_pessoa_documento",
        table_name="pessoa",
        postgresql_where=sa.text("documento IS NOT NULL"),
    )
    op.drop_index(
        "ix_pessoa_nome_normalizado_trgm",
        table_name="pessoa",
        postgresql_using="gin",
        postgresql_ops={"nome_normalizado": "gin_trgm_ops"},
    )
    op.drop_table("pessoa")
    op.drop_table("cliente")
    # ### end Alembic commands ###
