"""Acesso à API e ao painel (seção 8): usuários, sessões e chaves de API.

- usuario: senha Argon2 + TOTP obrigatório; cliente (com cliente_id) ou operador.
- sessao_usuario e chave_api: tokens guardados só como hash SHA-256.
Só monitor_sistema acessa estas tabelas (usado apenas para autenticar); depois da
autenticação a requisição roda como monitor_api sob RLS do cliente.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-24
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chave_api",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=False),
        sa.Column("prefixo", sa.String(length=12), nullable=False),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("descricao", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "criada_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("revogada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_uso_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_chave_api_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chave_api")),
        sa.UniqueConstraint("hash", name=op.f("uq_chave_api_hash")),
    )
    op.create_index(op.f("ix_chave_api_cliente_id"), "chave_api", ["cliente_id"], unique=False)
    op.create_table(
        "usuario",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("cliente_id", sa.BigInteger(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("senha_hash", sa.Text(), nullable=False),
        sa.Column("totp_segredo", sa.String(length=64), nullable=False),
        sa.Column("totp_ultimo_passo", sa.BigInteger(), nullable=True),
        sa.Column("papel", sa.String(length=10), server_default="cliente", nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("falhas_login", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bloqueado_ate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_login_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "(papel = 'cliente' AND cliente_id IS NOT NULL)"
            " OR (papel = 'operador' AND cliente_id IS NULL)",
            name=op.f("ck_usuario_papel_cliente"),
        ),
        sa.CheckConstraint("papel IN ('cliente', 'operador')", name=op.f("ck_usuario_papel")),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_usuario_email_minusculo")),
        sa.ForeignKeyConstraint(
            ["cliente_id"], ["cliente.id"], name=op.f("fk_usuario_cliente_id_cliente")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuario")),
        sa.UniqueConstraint("email", name=op.f("uq_usuario_email")),
    )
    op.create_index(op.f("ix_usuario_cliente_id"), "usuario", ["cliente_id"], unique=False)
    op.create_table(
        "sessao_usuario",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("usuario_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "criada_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revogada_em", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
            name=op.f("fk_sessao_usuario_usuario_id_usuario"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessao_usuario")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessao_usuario_token_hash")),
    )
    op.create_index(
        op.f("ix_sessao_usuario_usuario_id"), "sessao_usuario", ["usuario_id"], unique=False
    )
    # ### end Alembic commands ###
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON usuario, sessao_usuario, chave_api "
        "TO monitor_sistema"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessao_usuario_usuario_id"), table_name="sessao_usuario")
    op.drop_table("sessao_usuario")
    op.drop_index(op.f("ix_usuario_cliente_id"), table_name="usuario")
    op.drop_table("usuario")
    op.drop_index(op.f("ix_chave_api_cliente_id"), table_name="chave_api")
    op.drop_table("chave_api")
    # ### end Alembic commands ###
