"""Saúde dos robôs (seção 9): sentinelas, execuções de sentinela e alarmes.

- sentinela: processo público conhecido e os campos esperados da capa.
- execucao_sentinela: resultado de cada conferência horária.
- alarme: no máximo um aberto por (tribunal, tipo) — índice único parcial.
Só monitor_sistema acessa (a API lê pela sessão de operador).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarme",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column("tipo", sa.String(length=20), nullable=False),
        sa.Column(
            "aberto_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolvido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "detalhes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tipo IN ('sentinela', 'taxa_erro', 'volume_baixo')", name=op.f("ck_alarme_tipo")
        ),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_alarme_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alarme")),
    )
    op.create_index(
        "uq_alarme_aberto",
        "alarme",
        ["tribunal_id", "tipo"],
        unique=True,
        postgresql_where=sa.text("resolvido_em IS NULL"),
    )
    op.create_table(
        "sentinela",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("tribunal_id", sa.BigInteger(), nullable=False),
        sa.Column("numero_cnj", sa.String(length=25), nullable=False),
        sa.Column(
            "campos_esperados",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "numero_cnj ~ '^\\d{7}-\\d{2}\\.\\d{4}\\.\\d\\.\\d{2}\\.\\d{4}$'",
            name=op.f("ck_sentinela_numero_cnj_formato"),
        ),
        sa.ForeignKeyConstraint(
            ["tribunal_id"], ["tribunal.id"], name=op.f("fk_sentinela_tribunal_id_tribunal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sentinela")),
        sa.UniqueConstraint(
            "tribunal_id", "numero_cnj", name=op.f("uq_sentinela_tribunal_id_numero_cnj")
        ),
    )
    op.create_table(
        "execucao_sentinela",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("sentinela_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "executada_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sucesso", sa.Boolean(), nullable=False),
        sa.Column("duracao_ms", sa.Integer(), nullable=True),
        sa.Column(
            "divergencias",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sentinela_id"],
            ["sentinela.id"],
            name=op.f("fk_execucao_sentinela_sentinela_id_sentinela"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execucao_sentinela")),
    )
    op.create_index(
        "ix_execucao_sentinela_sentinela_executada",
        "execucao_sentinela",
        ["sentinela_id", "executada_em"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON sentinela, execucao_sentinela, alarme "
        "TO monitor_sistema"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_execucao_sentinela_sentinela_executada", table_name="execucao_sentinela")
    op.drop_table("execucao_sentinela")
    op.drop_table("sentinela")
    op.drop_index(
        "uq_alarme_aberto", table_name="alarme", postgresql_where=sa.text("resolvido_em IS NULL")
    )
    op.drop_table("alarme")
    # ### end Alembic commands ###
